Repository pre-onboarding-4th-team-H/01-Community-H, pull requests merged in 2022-09, with the labels that each got.

#13 Create User / #8 / Feat: Add User API
  .eslintrc.json
  app.js
  codes/errorCodes.js
  controllers/index.js
  dao/userJoinDao.js
  database/models/user.js
  database/models/users.js
  middlewares/errorHandler.js
  middlewares/validator/index.js
  middlewares/validator/userValidator.js
  package-lock.json
  package.json
  repos/index.js
  repos/user.js
  routes/index.js
  routes/user.js
  services/index.js
  services/user.js
Labels: major, feature

#14 Feat: #9 / Feat: Add noticeBoard API
  .eslintrc.json
  app.js
  middlewares/adminRequired.js
  middlewares/errorHandler.js
  middlewares/validator/boardValidator.js
  middlewares/validator/passwordValidator.js
  package.json
  repos/index.js
  repos/notice.js
  routes/board.js
  routes/index.js
  services/index.js
  services/notice.js
Labels: major, feature

#19 Test / #18 / Test : Creat User API
  .eslintrc.json
  __test__/join.test.js
  app.js
  package-lock.json
  package.json
  server.js
Labels: major, test

#21 Feature / User login
  package-lock.json
  package.json
  repos/user.js
  routes/user.js
  services/user.js
Labels: major, feature

#23 Refactor / #22 / Refactor : board
  middlewares/adminRequired.js
  middlewares/loginRequired.js
  package-lock.json
  repos/board.js
  repos/user.js
  routes/freeBoard.js
  routes/noticeBoard.js
  routes/operateBoard.js
  services/freeBoard.js
  services/noticeBoard.js
  services/operateBoard.js
Labels: major, refactor, feature

#25 Feature / #24 / feature : delete User API
  app.js
  codes/errorCodes.js
  middlewares/loginRequired.js
  repos/user.js
  routes/index.js
  routes/user.js
  services/user.js
Labels: major, feature

#20 [review-needed] / Feat: swagger api docs
  app.js
  database/config.js
  repos/board.js
  routes/freeBoard.js
  services/freeBoard.js
  swagger/swagger.js
Labels: feature

#29 Test / write test code in user, boards
  __test__/delete_user.test.js
  __test__/freeCRUD.test.js
  __test__/login.test.js
  __test__/noticeCRUD.test.js
  __test__/operateCRUD.test.js
  routes/user.js
  services/freeBoard.js
Labels: major, test

#27 Feature / Patch User API
  codes/errorCodes.js
  dao/userChangeDao.js
  middlewares/validator/userValidator.js
  repos/user.js
  routes/user.js
  services/user.js
Labels: major, feature

#30 Docs / add swagger for User API
  routes/user.js
Labels: minor, document
